QLVuKhiTrangBi/Controllers/DonDeNghiController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QLVuKhiTrangBi.Data;
using QLVuKhiTrangBi.Models;
using System;
using System.Linq;

namespace QLVuKhiTrangBi.Controllers
{

    public class DonDeNghiController : Controller
    {
        QlvuKhiTrangBiContext db = new QlvuKhiTrangBiContext();
        [Authorize(Policy = "RequireDaiDoi")]
        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Policy = "RequireTieuDoan")]
        public IActionResult TieuDoan()
        {
            return View();
        }
        [Authorize(Policy = "RequireTroLy")]
        public IActionResult TroLy()
        {
            return View();
        }
        [Authorize(Policy = "RequireDaiDoi")]
        public PartialViewResult DSDNDaiDoi()
        {
            var tenDn = HttpContext.Session.GetString("UserName");
            var daidoi = (
            from tk in db.TaiKhoans
            join c in db.CanBoDaiDois on tk.MaQn equals c.MaQn
            where tk.TenDn == tenDn
            select c.MaDaiDoiNavigation.TenDaiDoi
            ).FirstOrDefault();
            ViewBag.daidoi = daidoi;
            var madd = (
            from tk in db.TaiKhoans
            join c in db.CanBoDaiDois on tk.MaQn equals c.MaQn
            where tk.TenDn == tenDn
            select c.MaDaiDoi
            ).FirstOrDefault();

            var dsyc = db.Yeucaumuonvktbs.Where(yc => yc.MaDaiDoi == madd).Include(yc => yc.MaCanBoDaiDoiNavigation).ToList();
            return PartialView("_dsyc", dsyc);
        }
        [Authorize(Policy = "RequireDaiDoi")]
        public IActionResult Create()
        {
            var dsLoaiSung = db.LoaiSungs.ToList();
            ViewBag.dsLoaiSung = dsLoaiSung;
            var dsTB = db.TrangBis.ToList();
            ViewBag.dsTB = dsTB;

            var tenDn = HttpContext.Session.GetString("UserName");
            var canbo = (
               from tk in db.TaiKhoans
               join c in db.CanBoDaiDois on tk.MaQn equals c.MaQn
               where tk.TenDn == tenDn
               select c.HoTen
               ).FirstOrDefault();
            ViewBag.canbo = canbo;

            var daidoi = (
            from tk in db.TaiKhoans
            join c in db.CanBoDaiDois on tk.MaQn equals c.MaQn
            where tk.TenDn == tenDn
            select c.MaDaiDoiNavigation.MaDaiDoi
            ).FirstOrDefault();
            ViewBag.daidoi = daidoi;

            return View();
        }
        [HttpPost]
        [Authorize(Policy = "RequireDaiDoi")]
        public IActionResult Create(Yeucaumuonvktb model, List<string> MaLoaiSung, List<int> slLoaiSung, List<string> MaTrangBi, List<int> slTrangBi)
        {

            var tenDn = HttpContext.Session.GetString("UserName");
            var yeuCauMuon = new Yeucaumuonvktb
            {
                MaDaiDoi = model.MaDaiDoi,
                MaCanBoDaiDoi = tenDn,
                ThoiGianDuKienMuon = model.ThoiGianDuKienMuon,
                ThoiGianDuKienTra = model.ThoiGianDuKienTra,
                TrangThai = "Chờ xác nhận",
                GhiChu = model.GhiChu,
                TenYc = model.TenYc,
            };

            db.Yeucaumuonvktbs.Add(yeuCauMuon);
            db.SaveChanges();

            for (int i = 0; i < MaLoaiSung.Count; i++)
            {
                var detailSung = new YeucauLoaisung
                {
                    MaYc = yeuCauMuon.MaYc,
                    MaLoaiSung = MaLoaiSung[i],
                    SoLuong = slLoaiSung[i]
                };
                db.YeucauLoaisungs.Add(detailSung);
            }

            for (int i = 0; i < MaTrangBi.Count; i++)
            {
                var detailTB = new YeucauLoaitb
                {
                    MaYc = yeuCauMuon.MaYc,
                    MaTrangBi = MaTrangBi[i],
                    SoLuong = slTrangBi[i]
                };
                db.YeucauLoaitbs.Add(detailTB);
            }

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize(Policy = "RequireTieuDoan")]
        public IActionResult ChiTiet(int id)
        {
            var yc = db.Yeucaumuonvktbs.SingleOrDefault(yc => yc.MaYc == id);
            ViewBag.yc = yc;
            var ycSung = db.YeucauLoaisungs.Where(yc => yc.MaYc == id).ToList();
            ViewBag.ycSung = ycSung;
            var ycTB = db.YeucauLoaitbs.Where(yc => yc.MaYc == id).ToList();
            ViewBag.ycTB = ycTB;

            return View();
        }
        [Authorize(Policy = "RequireTieuDoan")]
        public PartialViewResult DSDNTieuDoan()
        {
            var tenDn = HttpContext.Session.GetString("UserName");
            var daidoi = (
            from tk in db.TaiKhoans
            join c in db.CanBoDaiDois on tk.MaQn equals c.MaQn
            where tk.TenDn == tenDn
            select c.MaDaiDoiNavigation.TenDaiDoi
            ).FirstOrDefault();
            ViewBag.daidoi = daidoi;

            var dsyc = db.Yeucaumuonvktbs.Include(yc => yc.MaCanBoDaiDoiNavigation).ToList();
            return PartialView("_dsyctd", dsyc);
        }

        [HttpPost]
        [Authorize(Policy = "RequireTieuDoan")]
        public ActionResult AcceptRequest(int requestId)
        {
            var yc = db.Yeucaumuonvktbs.Find(requestId);

            yc.TrangThai = "Đã được duyệt";
            db.Yeucaumuonvktbs.Update(yc);
            db.SaveChanges();

            return Json(new { success = true });
        }

        [HttpPost]
        [Authorize(Policy = "RequireTieuDoan")]
        public ActionResult RejectRequest(int requestId)
        {
            var yc = db.Yeucaumuonvktbs.Find(requestId);

            yc.TrangThai = "Đề nghị bị từ chối";
            db.Yeucaumuonvktbs.Update(yc);
            db.SaveChanges();

            return Json(new { success = true });
        }

        [Authorize(Policy = "RequireTroLy")]
        public PartialViewResult DSDNTroLy()
        {
            var dsyc = db.Yeucaumuonvktbs.Where(y => y.TrangThai == "Đã được duyệt").Include(yc => yc.MaCanBoDaiDoiNavigation).ToList();
            return PartialView("_dsyctl", dsyc);
        }
        [Authorize(Policy = "RequireTroLy")]
        public IActionResult ChoMuon(int id)
        {
            var yc = db.Yeucaumuonvktbs.SingleOrDefault(yc => yc.MaYc == id);
            ViewBag.yc = yc;
            var ycSung = db.YeucauLoaisungs.Where(yc => yc.MaYc == id).ToList();
            ViewBag.ycSung = ycSung;
            var ycTB = db.YeucauLoaitbs.Where(yc => yc.MaYc == id).ToList();
            ViewBag.ycTB = ycTB;
            var dsCBc = db.CanBoDaiDois.Where(c => c.MaDaiDoi == yc.MaDaiDoi).ToList();
            ViewBag.dsCBc = dsCBc;

            //var dsLoaiSung = db.LoaiSungs.ToList();
            //ViewBag.dsLoaiSung = dsLoaiSung;

            var dsSung = db.Sungs.Where(s => s.SuDung == true).ToList();
            ViewBag.dsSung = dsSung;

            var dsTB = db.TrangBis.ToList();
            ViewBag.dsTB = dsTB;

            return View();
        }
        [HttpPost]
        [Authorize(Policy = "RequireTroLy")]
        public IActionResult ChoMuon(int mayc, string nguoigiao, string cbDaiDoi, string MaDaiDoi,
            List<string> soSung, List<string> tinhtrangmuon, List<string> tinhtrangmuonTB, List<string> MaTrangBi, List<int> soluong)
        {
            // biên bản mượn trả theo yêu cầu từ đại đội
            var obj = new BbmuonTraVktb()
            {
                TenBienBan = "Bàn giao vũ khí, trang bị, thực hiện nhiệm vụ (Yêu cầu " + mayc + ")",
                DaiDoi = MaDaiDoi,
                CbkhoGiao = nguoigiao,
                CbdaidoiNhan = cbDaiDoi,
                ThoiGianMuon = DateTime.Now.ToString(),
            };
            db.BbmuonTraVktbs.Add(obj);
            db.SaveChanges();

            // nếu mượn thì mượn trả bằng 1, trả thì bằng 0 
            for (int i = 0; i < soSung.Count; i++)
            {
                var objSung = new BbmuonTraSung()
                {
                    MaBienBan = obj.MaBienBan,
                    SoHieuSung = soSung[i],
                    MuonTra = 1,
                    TinhTrang = tinhtrangmuon[i],
                };
                db.BbmuonTraSungs.Add(objSung);

                // ghi nhận súng đang được dùng
                var s = db.Sungs.SingleOrDefault(s => s.SoHieuSung == soSung[i]);
                s.SuDung = false;
                s.GhiChu = "Đang sử dụng";
                db.Sungs.Update(s);
            }
            for (int i = 0; i < MaTrangBi.Count; i++)
            {
                var objTB = new BbmuonTraTb()
                {
                    MaBienBan = obj.MaBienBan,
                    MaTrangBi = MaTrangBi[i],
                    SoLuong = soluong[i],
                    MuonTra = 1,
                    TinhTrang = tinhtrangmuonTB[i],
                };
                db.BbmuonTraTbs.Add(objTB);

                // ghi nhận số lượng trang bị đang được dùng hoặc không dùng được nữa
                var tb = db.TrangBis.SingleOrDefault(m => m.MaTrangBi == MaTrangBi[i]);
                tb.KhongDungDuoc += soluong[i];
                tb.GhiChu += soluong[i] + "đang sử dụng";
                db.TrangBis.Update(tb);
            }
            db.SaveChanges();

            var yc = db.Yeucaumuonvktbs.Find(mayc);
            yc.GhiChu = "Đang mượn";
            db.Yeucaumuonvktbs.Update(yc);
            db.SaveChanges();

            return View();
        }
        [Authorize(Policy = "RequireTroLy")]
        public IActionResult TraVKTB(int id)
        {
            var yc = db.Yeucaumuonvktbs.SingleOrDefault(yc => yc.MaYc == id);
            ViewBag.yc = yc;

            var ten = "Bàn giao vũ khí, trang bị, thực hiện nhiệm vụ (Yêu cầu " + id + ")" ;
            var bbMuonTra = db.BbmuonTraVktbs.Where(m => m.TenBienBan == ten).SingleOrDefault();

QLVuKhiTrangBi/Views/DonDeNghi/ChiTiet.cshtml
@{
    ViewData["Title"] = "ChiTiet";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var yc = ViewBag.yc;
    var ycSung = ViewBag.ycSung;
    var ycTB = ViewBag.ycTB;
}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title"><b>Số lượng vũ khí, trang bị, vật chất có thể sử dụng</b></h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        còn....
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>


<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h2 class="card-title w-100">
                            <b>Chi tiết đơn đề nghị mượn vũ khí, trang bị, vật chất của @yc.MaDaiDoi</b>
                        </h2>
                        <div class="row">
                            <span style="color:black" class="col-6">
                                Thời gian dự kiến mượn: @yc.ThoiGianDuKienMuon <br />
                                Thời gian dự kiến trả: @yc.ThoiGianDuKienTra
                            </span>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Nội dung</th>
                                    <th>Chi tiết (SL)</th>
                                    <th>Ghi chú</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var s in ycSung)
                                {
                                    <tr>
                                        <td>
                                            <div>
                                                <strong>@s.MaLoaiSung</strong>
                                            </div>
                                        </td>
                                        <td>@s.SoLuong (khẩu)</td>
                                        <td>@s.GhiChu</td>
                                    </tr>

                                }
                                @foreach (var tb in ycTB)
                                {
                                    <tr>
                                        <td>
                                            <div>
                                                <strong>@tb.MaTrangBi</strong>
                                            </div>
                                        </td>
                                        <td>@tb.SoLuong (cái)</td>
                                        <td>@tb.GhiChu</td>
                                    </tr>

                                }
                            </tbody>
                        </table>

                        <div class="form-group row mt-3">
                            <a class="btn btn-secondary col-sm-1" href="@Url.Action("TieuDoan", "DonDeNghi")">Quay lại</a>
                            <div class="col-sm-8"></div>
                            <button class="btn btn-primary col-sm-1 accept-btn" id="accept">Xác nhận</button>
                            <div class="col-sm-1"></div>
                            <button class="btn btn-danger col-sm-1 reject-btn" id="reject">Từ chối</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script>
        $(document).on('click', '.accept-btn', function () {
            $.ajax({
                url: '@Url.Action("AcceptRequest", "DonDeNghi")',
                type: 'POST',
                data: { requestId: '@yc.MaYc' },
                success: function (data) {
                    console.log('Request accepted successfully');
                    window.location.href = '@Url.Action("TieuDoan", "DonDeNghi")';
                },
                error: function (error) {
                    console.error('Error accepting request:', error);
                }
            });
        });
        $(document).on('click', '.reject-btn', function () {
            $.ajax({
                url: '@Url.Action("RejectRequest", "DonDeNghi")',
                type: 'POST',
                data: { requestId: '@yc.MaYc' },
                success: function (data) {
                    console.log('Request accepted successfully');
                    window.location.href = '@Url.Action("TieuDoan", "DonDeNghi")';
                },
                error: function (error) {
                    console.error('Error accepting request:', error);
                }
            });
        });
    </script>
}

QLVuKhiTrangBi/Views/DonDeNghi/Create.cshtml
@model QLVuKhiTrangBi.Models.Yeucaumuonvktb

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var jsonDsLoaiSung = Newtonsoft.Json.JsonConvert.SerializeObject(ViewBag.dsLoaiSung);
    var jsonDsTB = Newtonsoft.Json.JsonConvert.SerializeObject(ViewBag.dsTB);
}

<section class="content">
    <div class="container-fluid">
        <form asp-action="Create" method="post" >
            <div class="row">

                <div class="col-6">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Thêm yêu cầu mượn vũ khí trang bị</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">

                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group row">
                                <label asp-for="MaDaiDoi" class="col-sm-4 col-form-label">Mã đại đội</label>
                                <div class="col-sm-7">
                                    <input asp-for="MaDaiDoi" class="form-control" name="MaDaiDoi" value="@ViewBag.daidoi" />
                                </div>
                                <span asp-validation-for="MaDaiDoi" class="text-danger"></span>
                            </div>
                            <div class="form-group row">
                                <label asp-for="MaCanBoDaiDoi" class="col-sm-4 col-form-label">Cán bộ đại đội</label>
                                <div class="col-sm-7">
                                    <input asp-for="MaCanBoDaiDoi" class="form-control" name="MaCanBoDaiDoi" value="@ViewBag.canbo"/>
                                </div>
                                <span asp-validation-for="MaCanBoDaiDoi" class="text-danger"></span>
                            </div>
                            <div class="form-group row">
                                <label asp-for="ThoiGianDuKienMuon" class="col-sm-4 col-form-label">Thời gian dự kiến mượn</label>
                                <div class="col-sm-7">
                                    <input asp-for="ThoiGianDuKienMuon" class="form-control" name="ThoiGianDuKienMuon" />
                                </div>
                                <span asp-validation-for="ThoiGianDuKienMuon" class="text-danger"></span>
                            </div>
                            <div class="form-group row">
                                <label asp-for="ThoiGianDuKienTra" class="col-sm-4 col-form-label">Thời gian dự kiến trả</label>
                                <div class="col-sm-7">
                                    <input asp-for="ThoiGianDuKienTra" class="form-control" name="ThoiGianDuKienTra" />
                                </div>
                                <span asp-validation-for="ThoiGianDuKienTra" class="text-danger"></span>
                            </div>
                            <div class="form-group row">
                                <label asp-for="TenYc" class="col-sm-4 col-form-label">Lý do mượn</label>
                                <div class="col-sm-7">
                                    <input asp-for="TenYc" class="form-control" name="TenYc" />
                                </div>
                                <span asp-validation-for="TenYc" class="text-danger"></span>
                            </div>
                            <div class="form-group row">
                                <label asp-for="GhiChu" class="col-sm-4 col-form-label">Ghi chú</label>
                                <div class="col-sm-7">
                                    <input asp-for="GhiChu" class="form-control" name="GhiChu" />
                                </div>
                                <span asp-validation-for="GhiChu" class="text-danger"></span>
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-3"></div>
                                <input type="submit" value="Xác nhận" class="btn btn-primary col-sm-2" />
                                <div class="col-sm-1"></div>
                                <input type="reset" value="Hủy bỏ" class="btn btn-danger col-sm-2" />
                            </div>
                            <span class="text-danger">
                                @ViewBag.Message
                            </span>

                        </div>
                    </div>
                </div>

                <div class="col-6">
                    <div class="card card-info">
                        <div class="card-header">
                            <h3 class="card-title">Súng cần mượn</h3>
                        </div>
                        <div class="card-body">
                            <div class="form-group row">
                                <label class="col-2 col-form-label">Loại Súng</label>
                                <div class="col-sm-4">
                                    <select name="MaLoaiSung" class="form-control">
                                        <option value="" class="form-control"></option>
                                        @foreach (var item in ViewBag.dsLoaiSung)
                                        {
                                            <option value="@item.MaLoaiSung" class="form-control">@item.TenLoaiSung</option>
                                        }
                                    </select>
                                </div>
                                <label class="col-sm-2 col-form-label">Số lượng</label>
                                <input type="number" class="col-sm-2 form-control" name="slLoaiSung" />
                                <div class="col-sm-1"></div>
                                <input type="button" value="Xóa" class="btn btn-danger col-1" id="removeSectionButton" />
                            </div>
                            <div id="dynamicSectionsContainer"></div>
                        
                            <div class="form-group row">
                                <div class="col-sm-5"></div>
                                <input type="button" value="Thêm tiếp" class="btn btn-success col-sm-2" id="addSectionButton" />
                             </div>
                        </div>
                    </div>

                    <div class="card card-info">
                        <div class="card-header">
                            <h3 class="card-title">Trang bị cần mượn</h3>
                        </div>
                        <div class="card-body">
                            <div class="form-group row">
                                <label class="col-2 col-form-label">Trang bị</label>
                                <div class="col-sm-4">
                                    <select name="MaTrangBi" class="form-control">
                                        <option value="" class="form-control"></option>
                                        @foreach (var item in ViewBag.dsTB)
                                        {
                                            <option value="@item.MaTrangBi" class="form-control">@item.TenTrangBi</option>
                                        }
                                    </select>
                                </div>
                                <label class="col-sm-2 col-form-label">Số lượng</label>
                                <input type="number" class="col-sm-2 form-control" name="slTrangBi" />
                                <div class="col-sm-1"></div>
                                <input type="button" value="Xóa" class="btn btn-danger col-1" id="removeTBButton" />
                            </div>
                            <div id="addTB"></div>
                            <div class="form-group row">
                                <div class="col-sm-5"></div>
                                <input type="button" value="Thêm tiếp" class="btn btn-success col-sm-2" id="addTbButton" />
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </form>
    </div>
</section>



<div id="allDonDeNghi"></div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#allDonDeNghi').load('/DonDeNghi/DSDNDaiDoi');

            $('#addSectionButton').click(function () {
                addSection();
            });

            $('#addTbButton').click(function () {
                addTBSection();
            });
           
        });
        var sectionCounter = 0;
        var maxSections = @ViewBag.dsLoaiSung.Count-1;
        var dsLoaiSungOptions = JSON.parse('@Html.Raw(jsonDsLoaiSung)');
        //var sectionData = [];

        function addSection() {
            if (sectionCounter < maxSections) {
                sectionCounter++;

                var html = '<div class="form-group row">';
                html += '<label class="col-2 col-form-label">Loại Súng</label>';
                html += '<div class="col-sm-4">';
                html += '<select name="MaLoaiSung" class="form-control">';

                dsLoaiSungOptions.forEach(function (item) {
                    html += '<option value="' + item.MaLoaiSung + '">' + item.TenLoaiSung + '</option>';
                });

                html += '</select>';
                html += '</div>';
                html += '<label class="col-sm-2 col-form-label">Số lượng</label>';
                html += '<input type="number" class="col-sm-2 form-control" name="slLoaiSung" />';
                html += '<div class="col-sm-1"></div>';
                html += '<input type="button" value="Xóa" class="btn btn-danger col-1 removeSectionButton"/>';
                html += '</div>';

                $('#dynamicSectionsContainer').append(html);

            } else {
                $('#addSectionButton').hide();
            }
        }


        var sectionCounterTB = 0;
        var maxSectionsTB = @ViewBag.dsTB.Count-1;
        var dsTBOptions = JSON.parse('@Html.Raw(jsonDsTB)');
        function addTBSection() {
            if (sectionCounterTB < maxSectionsTB) {
                sectionCounterTB++;

                var html = '<div class="form-group row">';
                html += '<label class="col-2 col-form-label">Trang bị</label>';
                html += '<div class="col-sm-4">';
                html += '<select name="MaTrangBi" class="form-control">';

                // Add options to the select element
                dsTBOptions.forEach(function (item) {
                    html += '<option value="' + item.MaTrangBi + '">' + item.TenTrangBi + '</option>';
                });

                html += '</select>';
                html += '</div>';
                html += '<label class="col-sm-2 col-form-label">Số lượng</label>';
                html += '<input type="number" class="col-sm-2 form-control" name="slTrangBi" />';
                html += '<div class="col-sm-1"></div>';
                html += '<input type="button" value="Xóa" class="btn btn-danger col-1" id="removeTBButton"/>';
                html += '</div>';

                // Append the new HTML section to the container
                $('#addTB').append(html);

            } else {
                $('#addTbButton').hide();
            }
        }

        // Add click event for removing sections
        $(document).on('click', '#removeSectionButton', function () {
            $(this).closest('.form-group').remove();
        });

        // Add click event for removing TB sections
        $(document).on('click', '#removeTBButton', function () {
            $(this).closest('.form-group').remove();
        });

        //$('#submitFormButton').click(function () {
        //    // Serialize dữ liệu từ form chính
        //    var formData = $('#mainForm').serialize();

        //    // Thực hiện yêu cầu Ajax
        //    $.ajax({
        //        type: 'POST',
        //        url: '/DonDeNghi/Create',
        //        data: formData,
        //        success: function (result) {

        //        },
        //        error: function (error) {
        //            console.error('Error:', error);
        //        }
        //    });
        //});
    </script>
}

QLVuKhiTrangBi/Views/DonDeNghi/Index.cshtml
@model IEnumerable<QLVuKhiTrangBi.Models.Yeucaumuonvktb>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="d-flex justify-content-end m-3 mr-5">
    <a href="/DonDeNghi/Create" class="btn btn-primary">Thêm yêu cầu mới</a>
</div>


<div id="allDonDeNghi"></div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#allDonDeNghi').load('/DonDeNghi/DSDNDaiDoi');
        });
    </script>
}

QLVuKhiTrangBi/Views/DonDeNghi/TieuDoan.cshtml
@model IEnumerable<QLVuKhiTrangBi.Models.Yeucaumuonvktb>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="allDonDeNghi"></div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#allDonDeNghi').load('/DonDeNghi/DSDNTieuDoan');
        });
    </script>
    }

QLVuKhiTrangBi/Views/DonDeNghi/TroLy.cshtml
@model IEnumerable<QLVuKhiTrangBi.Models.Yeucaumuonvktb>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="allDonDeNghiDuyet"></div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#allDonDeNghiDuyet').load('/DonDeNghi/DSDNTroLy');
        });
    </script>
    }